### ISSUE TITLE
Npe while autofill

### ISSUE THREAD

**Issue by jenspfahl** [jenspfahl/ANOTHERpass#13]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<de.jepfa.yapm.model.encrypted.EncCredential?>
	at java.util.Objects.requireNonNull(Objects.java:245)
	at de.jepfa.yapm.ui.credential.ListCredentialAdapter$getFilter$1.publishResults(ListCredentialAdapter.kt:212)
	at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:284)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

************ APP INFORMATION ***********
Version: 1.6.0
Version Code: 106000
Database Version: 5
Vault Version: 1
Vault Cipher: AES_128
Build Timestamp: 27.02.2022 01:42:53
Build Type: release

************ DEVICE INFORMATION ***********
Brand: google
Manufacturer: Google
Device: sunfish
Model: Pixel 4a
Product: sunfish
Hardware: sunfish
OS Build Id: SQ1A.211205.008
NFC available: true
NFC enabled: true
Has StrongBox support: true
Has biometrics support: true
Is fingerprint enroled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Overlay dialog granted: false
Camera granted: true
Biometric granted: true

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7888514
Codename: REL
Security patch: 2021-12-05

**Comment by jenspfahl** [comment]
Seems to be related to Android 12

**Comment by jenspfahl** [comment]
Fixed with v1.6.1
