### ISSUE TITLE
Observe in use cases fail

### ISSUE THREAD

**Issue by jenspfahl** [jenspfahl/ANOTHERpass#19]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Cannot invoke observe on a background thread
	at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:487)
	at androidx.lifecycle.LiveData.observe(LiveData.java:191)
	at de.jepfa.yapm.util.ExtensionsKt.observeOnce(Extensions.kt:152)
	at de.jepfa.yapm.usecase.label.DeleteLabelUseCase.doExecute(DeleteLabelUseCase.kt:20)
	at de.jepfa.yapm.usecase.label.DeleteLabelUseCase.doExecute(DeleteLabelUseCase.kt:12)
	at de.jepfa.yapm.usecase.InputUseCase.execute(InputUseCase.kt:8)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$launch$2.invokeSuspend(UseCaseBackgroundLauncher.kt:24)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$launch$2.invoke(Unknown Source:8)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$launch$2.invoke(Unknown Source:2)
	at de.jepfa.yapm.ui.AsyncWithProgressBar$3.invokeSuspend(AsyncWithProgressBar.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

************ APP INFORMATION ***********
Version: 1.7.0_rc
Version Code: 107000
Database Version: 5
Vault Version: 2
Vault Cipher: AES_128
Build Timestamp: 30.07.2022 22:55:50
Build Type: debug

************ DEVICE INFORMATION ***********
Brand: samsung
Manufacturer: samsung
Device: a3y17lte
Model: SM-A320FL
Product: a3y17ltexc
Hardware: samsungexynos7870
OS Build Id: QQ3A.200805.001
NFC available: true
NFC enabled: true
Has StrongBox support: false
Has biometrics support: true
Is fingerprint enroled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Overlay dialog granted: false
Camera granted: true
Biometric granted: true

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.wistan.20220205.130213
Codename: REL
Security patch: 2022-01-05

**Comment by jenspfahl** [comment]
fixed in 1.7.0
