### ISSUE TITLE
Crypto error

### ISSUE THREAD

**Issue by jenspfahl** [jenspfahl/ANOTHERpass#22]
************ CAUSE OF ERROR ************

java.security.InvalidKeyException: Keystore operation failed
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException(KeyStoreCryptoOperationUtils.java:130)
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:154)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:339)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:171)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2985)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1144)
	at javax.crypto.Cipher.init(Cipher.java:1085)
	at de.jepfa.yapm.service.secret.SecretService.encryptData(SecretService.kt:201)
	at de.jepfa.yapm.service.secret.SecretService.encryptPassword(SecretService.kt:165)
	at de.jepfa.yapm.usecase.session.LoginUseCase.doExecute(LoginUseCase.kt:40)
	at de.jepfa.yapm.usecase.session.LoginUseCase.doExecute(LoginUseCase.kt:19)
	at de.jepfa.yapm.usecase.InputUseCase.execute(InputUseCase.kt:8)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$launch$2.invokeSuspend(UseCaseBackgroundLauncher.kt:24)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$launch$2.invoke(Unknown Source:8)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$launch$2.invoke(Unknown Source:2)
	at de.jepfa.yapm.ui.AsyncWithProgressBar$3.invokeSuspend(AsyncWithProgressBar.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: android.security.KeyStoreException: Device locked (internal Keystore code: -72 message: In create_operation.

Caused by:
    0: In authorize_create: device is locked.
    1: Error::Km(ErrorCode(-72))) (public error code: 2 internal Keystore code: -72)
	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:369)
	at android.security.KeyStoreSecurityLevel.createOperation(KeyStoreSecurityLevel.java:120)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:334)
	... 22 more

************ APP INFORMATION ***********
Version: 1.7.0_rc
Version Code: 107000
Database Version: 5
Vault Version: 1
Vault Cipher: AES_128
Build Timestamp: 17.09.2022 14:53:57
Build Type: debug

************ DEVICE INFORMATION ***********
Brand: google
Manufacturer: Google
Device: sunfish
Model: Pixel 4a
Product: sunfish
Hardware: sunfish
OS Build Id: TP1A.220905.004
NFC available: true
NFC enabled: true
Has StrongBox support: true
Has biometrics support: true
Is fingerprint enroled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: false
Overlay dialog granted: true
Camera granted: true
Biometric granted: true

************ FIRMWARE ************
SDK: 33
Release: 13
Incremental: 8927612
Codename: REL
Security patch: 2022-09-05

**Comment by jenspfahl** [comment]
Cannot reproduce. It seems this can happen from time to time caused by the OS.

**Comment by jenspfahl** [comment]
Cannot reproduce, never seen again
