### ISSUE TITLE
Error after flashing MPT on NFC 

### ISSUE THREAD

**Issue by jenspfahl** [jenspfahl/ANOTHERpass#23]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {de.jepfa.yapm/de.jepfa.yapm.ui.nfc.NfcActivity}: java.lang.SecurityException: Permission Denial: Tag ( ID: 04 0B BA BA 90 6B 81 ) is out of date
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5088)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5039)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4991)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:229)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:183)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:132)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.SecurityException: Permission Denial: Tag ( ID: 04 0B BA BA 90 6B 81 ) is out of date
	at android.nfc.Tag.getTagService(Tag.java:388)
	at android.nfc.tech.BasicTagTechnology.close(BasicTagTechnology.java:125)
	at android.nfc.tech.Ndef.close(Ndef.java:71)
	at de.jepfa.yapm.service.nfc.NdefTag.close(NdefTag.kt:99)
	at de.jepfa.yapm.ui.nfc.NfcBaseActivity.onPause(NfcBaseActivity.kt:32)
	at android.app.Activity.performPause(Activity.java:8466)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1585)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5078)
	... 15 more

************ APP INFORMATION ***********
Version: 1.7.0_rc
Version Code: 107000
Database Version: 5
Vault Version: 1
Vault Cipher: AES_128
Build Timestamp: 17.09.2022 22:06:49
Build Type: debug

************ DEVICE INFORMATION ***********
Brand: google
Manufacturer: Google
Device: sunfish
Model: Pixel 4a
Product: sunfish
Hardware: sunfish
OS Build Id: TP1A.220905.004
NFC available: true
NFC enabled: true
Has StrongBox support: true
Has biometrics support: true
Is fingerprint enroled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: false
Overlay dialog granted: true
Camera granted: true
Biometric granted: true

************ FIRMWARE ************
SDK: 33
Release: 13
Incremental: 8927612
Codename: REL
Security patch: 2022-09-05

**Comment by jenspfahl** [comment]
fixed
