### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by Anuranheady** [jenspfahl/ANOTHERpass#35]
************ CAUSE OF ERROR ************

java.security.ProviderException: Keystore key generation failed
	at android.security.keystore2.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:413)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
	at de.jepfa.yapm.service.secret.SecretService.initAndroidSecretKey(SecretService.kt:285)
	at de.jepfa.yapm.service.secret.SecretService.getAndroidSecretKey(SecretService.kt:246)
	at de.jepfa.yapm.ui.createvault.CreateVaultEnterPassphraseFragment.onViewCreated$lambda-7(CreateVaultEnterPassphraseFragment.kt:122)
	at de.jepfa.yapm.ui.createvault.CreateVaultEnterPassphraseFragment.$r8$lambda$YtCt-PGo7alsKyuinU0Of4KHlE8(Unknown Source:0)
	at de.jepfa.yapm.ui.createvault.CreateVaultEnterPassphraseFragment$$ExternalSyntheticLambda3.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29341)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.security.KeyStoreException: System error (internal Keystore code: 4 message: In generate_key.

Caused by:
    0: In store_new_key.
    1: In store_new_key. Failed to handle super encryption.
    2: In handle_super_encryption_on_key_init: User ECDH key missing.
    3: Error::Rc(ResponseCode(4))) (public error code: 4 internal Keystore code: 4)
	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:336)
	at android.security.KeyStoreSecurityLevel.handleExceptions(KeyStoreSecurityLevel.java:57)
	at android.security.KeyStoreSecurityLevel.generateKey(KeyStoreSecurityLevel.java:145)
	at android.security.keystore2.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:400)
	... 18 more

************ APP INFORMATION ***********
Version: 1.7.2
Version Code: 107002
Database Version: 5
Vault Version: 1
Vault Cipher: AES_128
Build Timestamp: 17-Dec-2022 6:42:01 am
Build Type: release

************ DEVICE INFORMATION ***********
Brand: google
Manufacturer: Google
Device: oriole
Model: Pixel 6
Product: oriole
Hardware: oriole
OS Build Id: TQ1A.221205.011
NFC available: true
NFC enabled: true
Has StrongBox support: true
Has biometrics support: true
Is fingerprint enroled: false

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Overlay dialog granted: false
Camera granted: false
Biometric granted: true

************ FIRMWARE ************
SDK: 33
Release: 13
Incremental: 9244662
Codename: REL
Security patch: 2022-12-05

**Comment by jenspfahl** [comment]
Is this behavior reproducible? It looks like a system error while generating a secret key by the OS itself. If it's only happening rarely, i could work around that bug.

**Comment by Anuranheady** [comment]
Yes, it happens everytime I try exporting a Master PW. I'm on a Pixel 6 on
the latest A13 beta.

**Comment by jenspfahl** [comment]
Okay, a beta version could include some bugs. This is definitely a bug in Android itself, so nothing what i could do about this.
