### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by ruafelianna** [jenspfahl/ANOTHERpass#37]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:AnotherPass/anotherpassvault-86nwwotu-2023-01-24.json flg=0x43 }} to activity {de.jepfa.yapm/de.jepfa.yapm.ui.exportvault.ExportVaultActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { act=action_exportVault cmp=de.jepfa.yapm/.service.io.FileIOService (has extras) }: app is in background uid UidRecord{f9975c7 u0a104 LAST bg:+21s743ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5782)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8676)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=action_exportVault cmp=de.jepfa.yapm/.service.io.FileIOService (has extras) }: app is in background uid UidRecord{f9975c7 u0a104 LAST bg:+21s743ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1744)
	at android.app.ContextImpl.startService(ContextImpl.java:1699)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at de.jepfa.yapm.ui.exportvault.ExportVaultActivity.onActivityResult(ExportVaultActivity.kt:97)
	at android.app.Activity.dispatchActivityResult(Activity.java:8541)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5775)
	... 11 more

************ APP INFORMATION ***********
Version: 1.7.2
Version Code: 107002
Database Version: 5
Vault Version: 2
Vault Cipher: AES_256
Build Timestamp: 17 дек. 2022 г. 04:12:01
Build Type: release

************ DEVICE INFORMATION ***********
Brand: HONOR
Manufacturer: HUAWEI
Device: HWBKL
Model: BKL-L09
Product: BKL-L09
Hardware: kirin970
OS Build Id: HUAWEIBKL-L09S
NFC available: true
NFC enabled: false
Has StrongBox support: false
Has biometrics support: true
Is fingerprint enroled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Overlay dialog granted: true
Camera granted: true
Biometric granted: true

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.177C10
Codename: REL
Security patch: 2020-04-01

**Comment by ruafelianna** [comment]
It happened when I tried to export my master key. I have managed to export it later though.
