### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by adb76** [jenspfahl/ANOTHERpass#40]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	... 1 more
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException(KeyStoreCryptoOperationUtils.java:128)
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:154)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:345)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:177)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2985)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1144)
	at javax.crypto.Cipher.init(Cipher.java:1085)
	at de.jepfa.yapm.service.secret.SecretService.encryptData(SecretService.kt:198)
	at de.jepfa.yapm.service.secret.SecretService.encryptPassword(SecretService.kt:162)
	at de.jepfa.yapm.ui.createvault.CreateVaultEnterPassphraseFragment.onViewCreated$lambda-7(CreateVaultEnterPassphraseFragment.kt:123)
	at de.jepfa.yapm.ui.createvault.CreateVaultEnterPassphraseFragment.$r8$lambda$YtCt-PGo7alsKyuinU0Of4KHlE8(Unknown Source:0)
	at de.jepfa.yapm.ui.createvault.CreateVaultEnterPassphraseFragment$$ExternalSyntheticLambda3.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7881)
	at android.widget.TextView.performClick(TextView.java:16201)
	at android.view.View.performClickInternal(View.java:7858)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30863)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	... 3 more

************ APP INFORMATION ***********
Version: 1.7.2
Version Code: 107002
Database Version: 5
Vault Version: 1
Vault Cipher: AES_128
Build Timestamp: 17.12.2022 02:12:01
Build Type: release

************ DEVICE INFORMATION ***********
Brand: samsung
Manufacturer: samsung
Device: r9q
Model: SM-G990B2
Product: r9q2xeea
Hardware: qcom
OS Build Id: TP1A.220624.014
NFC available: true
NFC enabled: true
Has StrongBox support: true
Has biometrics support: true
Is fingerprint enroled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Overlay dialog granted: false
Camera granted: false
Biometric granted: true

************ FIRMWARE ************
SDK: 33
Release: 13
Incremental: G990B2XXS1DVL1
Codename: REL
Security patch: 2022-12-01

**Comment by jenspfahl** [comment]
Hi and thank you for reporting this bug. One question: if this error reproducible are were you able to succeed the vault creation?

**Comment by adb76** [comment]
What is really strange, after the restart of my phone it suddenly worked out. So no, unfortunately I can not reproduce it anymore...
