### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by noname5551010** [jenspfahl/ANOTHERpass#41]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	... 1 more
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException(KeyStoreCryptoOperationUtils.java:128)
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:154)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:339)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:171)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2985)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1144)
	at javax.crypto.Cipher.init(Cipher.java:1085)
	at de.jepfa.yapm.service.secret.SecretService.encryptData(SecretService.kt:198)
	at de.jepfa.yapm.service.secret.SecretService.encryptPassword(SecretService.kt:162)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$onViewCreated$3$3.invoke(LoginEnterPinFragment.kt:130)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$onViewCreated$3$3.invoke(LoginEnterPinFragment.kt:125)
	at de.jepfa.yapm.service.secret.MasterPasswordService.getMasterPasswordFromStore(MasterPasswordService.kt:62)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.onViewCreated$lambda-3(LoginEnterPinFragment.kt:125)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.$r8$lambda$2L5oUcZAgJNXJDAtleYP0VvHNWg(Unknown Source:0)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:8)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29357)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	... 3 more

************ APP INFORMATION ***********
Version: 1.7.3
Version Code: 107003
Database Version: 5
Vault Version: 2
Vault Cipher: AES_128
Build Timestamp: Feb 1, 2023 17:45:36
Build Type: release

************ DEVICE INFORMATION ***********
Brand: google
Manufacturer: Google
Device: cheetah
Model: Pixel 7 Pro
Product: cheetah
Hardware: cheetah
OS Build Id: TQ2A.230305.008.C1
NFC available: true
NFC enabled: true
Has StrongBox support: true
Has biometrics support: true
Is fingerprint enroled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Overlay dialog granted: false
Camera granted: true
Biometric granted: true

************ FIRMWARE ************
SDK: 33
Release: 13
Incremental: 9619669
Codename: REL
Security patch: 2023-03-05

**Comment by jenspfahl** [comment]
This might happen when no screen lock is set for the device. Is this the case?

**Comment by jenspfahl** [comment]
Should be fixed with version 1.808
