### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by EdwardVanAdvert** [jenspfahl/ANOTHERpass#46]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1320303484, result=-1, data=Intent { act=inline-data (has extras) }} to activity {de.jepfa.yapm/de.jepfa.yapm.ui.createvault.CreateVaultActivity}: android.security.keystore.UserNotAuthenticatedException: User not authenticated
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5517)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5556)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2348)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8191)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException(KeyStoreCryptoOperationUtils.java:128)
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:154)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:339)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:171)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2985)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1144)
	at javax.crypto.Cipher.init(Cipher.java:1085)
	at de.jepfa.yapm.service.secret.SecretService.encrypt(SecretService.kt:227)
	at de.jepfa.yapm.service.secret.SecretService.encryptData(SecretService.kt:215)
	at de.jepfa.yapm.service.secret.SecretService.encryptKey(SecretService.kt:157)
	at de.jepfa.yapm.service.secret.SaltService.storeSalt(SaltService.kt:43)
	at de.jepfa.yapm.service.secret.SaltService.createAndStoreSalt(SaltService.kt:54)
	at de.jepfa.yapm.service.secret.SaltService.getSalt(SaltService.kt:27)
	at de.jepfa.yapm.usecase.secret.SeedRandomGeneratorUseCase.extractSeedFromImage(SeedRandomGeneratorUseCase.kt:109)
	at de.jepfa.yapm.usecase.secret.SeedRandomGeneratorUseCase.execute(SeedRandomGeneratorUseCase.kt:29)
	at de.jepfa.yapm.usecase.secret.SeedRandomGeneratorUseCase.execute(SeedRandomGeneratorUseCase.kt:24)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$launch$2.invokeSuspend(UseCaseBackgroundLauncher.kt:24)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$launch$2.invoke(Unknown Source:8)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$launch$2.invoke(Unknown Source:2)
	at de.jepfa.yapm.ui.AsyncWithProgressBar$result$1.invokeSuspend(AsyncWithProgressBar.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at de.jepfa.yapm.ui.AsyncWithProgressBar.<init>(AsyncWithProgressBar.kt:37)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher.launch(UseCaseBackgroundLauncher.kt:22)
	at de.jepfa.yapm.ui.createvault.CreateVaultEnterPassphraseFragment.onActivityResult(CreateVaultEnterPassphraseFragment.kt:150)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2698)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2678)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:793)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:152)
	at android.app.Activity.dispatchActivityResult(Activity.java:8487)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5510)
	... 13 more

************ APP INFORMATION ***********
Version: 1.8.1
Version Code: 108001
Database Version: 6
Vault Version: 1
Vault Cipher: AES_128
Build Timestamp: 07.07.2023 17:39:05
Build Type: release

************ DEVICE INFORMATION ***********
Brand: OPPO
Manufacturer: OPPO
Device: OP4C41L1
Model: CPH2005
Product: CPH2005EEA
Hardware: qcom
OS Build Id: RKQ1.211103.002
NFC available: true
NFC enabled: true
Has StrongBox support: false
Has biometrics support: true
Is fingerprint enrolled: false
Is device lock enabled: true

************ PERMISSIONS ************
Read Storage granted: false
Read/write storage granted: false
Notifications granted: true
Overlay dialog granted: false
Camera granted: true
Biometric granted: true

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: Q.GDPR.10c1ef0_666_668
Codename: REL
Security patch: 2023-06-05

**Comment by jenspfahl** [comment]
This should be fixed in the meantime.
