### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by linuxzsh** [jenspfahl/ANOTHERpass#51]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	... 1 more
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException(KeyStoreCryptoOperationUtils.java:128)
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:154)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:339)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:171)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2985)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1144)
	at javax.crypto.Cipher.init(Cipher.java:1085)
	at de.jepfa.yapm.service.secret.SecretService.encrypt(SecretService.kt:227)
	at de.jepfa.yapm.service.secret.SecretService.encryptData(SecretService.kt:215)
	at de.jepfa.yapm.service.secret.SecretService.encryptPassword(SecretService.kt:165)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$onViewCreated$3$3.invoke(LoginEnterPinFragment.kt:114)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$onViewCreated$3$3.invoke(LoginEnterPinFragment.kt:109)
	at de.jepfa.yapm.service.secret.MasterPasswordService.decryptWithBiometrics(MasterPasswordService.kt:226)
	at de.jepfa.yapm.service.secret.MasterPasswordService.getMasterPasswordFromStore(MasterPasswordService.kt:67)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.onViewCreated$lambda$2(LoginEnterPinFragment.kt:109)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.$r8$lambda$rE_szBT3zcIN3lUfwWmeZShNVww(Unknown Source:0)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:8)
	at android.view.View.performClick(View.java:7570)
	at android.view.View.performClickInternal(View.java:7540)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29710)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8427)
	... 3 more

************ APP INFORMATION ***********
Version: 1.8.1
Version Code: 108001
Database Version: 6
Vault Version: 2
Vault Cipher: AES_256
Build Timestamp: 7 juil. 2023 5:39:05 PM
Build Type: release

************ DEVICE INFORMATION ***********
Brand: realme
Manufacturer: realme
Device: RE879AL1
Model: RMX3370
Product: RMX3370EEA
Hardware: qcom
OS Build Id: TP1A.220905.001
NFC available: true
NFC enabled: false
Has StrongBox support: false
Has biometrics support: true
Is fingerprint enrolled: true
Is device lock enabled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Notifications granted: true
Overlay dialog granted: true
Camera granted: true
Biometric granted: true

************ FIRMWARE ************
SDK: 33
Release: 13
Incremental: R.12f334c_84945-2
Codename: REL
Security patch: 2023-09-05

**Comment by linuxzsh** [comment]
Sorry, I can't intentionally reproduce this error. This crash appeared several times in a row preventing me from using the app. I don't remember any particular manipulations on my part; Normal use. A reboot solved the problem.

Le 13 novembre 2023 19:56:33 GMT+01:00, Jens Pfahl ***@***.***> a écrit :

**Comment by jenspfahl** [comment]
Ok, thank you. I will update the used libraries to the recent version, because the current I use is depreciated. I hope this will solve this issue.
