### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by Rafaelaldon** [jenspfahl/ANOTHERpass#56]
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 268173320 byte allocation with 25165824 free bytes and 252MB until OOM, target footprint 163130976, growth limit 402653184
	at java.util.Arrays.copyOf(Arrays.java:3766)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:449)
	at java.lang.StringBuilder.append(StringBuilder.java:137)
	at de.jepfa.yapm.util.FileUtil.readFile(FileUtil.kt:44)
	at de.jepfa.yapm.ui.importvault.ImportVaultLoadFileFragment.onActivityResult(ImportVaultLoadFileFragment.kt:77)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2698)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2678)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:793)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:152)
	at android.app.Activity.dispatchActivityResult(Activity.java:8472)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5561)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5607)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8249)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

************ APP INFORMATION ***********
Version: 1.8.2
Version Code: 108002
Database Version: 6
Vault Version: 1
Vault Cipher: AES_128
MP stored: false
MP stored with auth: false
Build Timestamp: 18 nov. 2023 4:40:18 p. m.
Build Type: release

************ DEVICE INFORMATION ***********
Brand: OPPO
Manufacturer: OPPO
Device: OP56F5
Model: CPH2477
Product: CPH2477T2
Hardware: mt6765
OS Build Id: SP1A.210812.016
NFC available: false
NFC enabled: false
Has StrongBox support: false
Has biometrics support: true
Has biometrics enrolled: true
Is device lock enabled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: false
Notifications granted: true
Overlay dialog granted: false
Camera granted: false
Biometric granted: true

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: S.202310092141
Codename: REL
Security patch: 2023-10-05

**Comment by jenspfahl** [comment]
The file you tried to upload was 263MB big. I assume this was not a backup file but something else by mistake?

**Comment by Rafaelaldon** [comment]
El protocolos

**Comment by jenspfahl** [comment]
Fixed with V1.9.x
