### ISSUE TITLE
Something went wrong :-(

### ISSUE THREAD

**Issue by matt-the-bat** [jenspfahl/ANOTHERpass#64]
Any chance I can recover my data?
************ CAUSE OF ERROR ************

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:614)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	... 1 more
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException(KeyStoreCryptoOperationUtils.java:128)
	at android.security.keystore2.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:154)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:345)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:177)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2985)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1144)
	at javax.crypto.Cipher.init(Cipher.java:1085)
	at de.jepfa.yapm.service.secret.SecretService.encrypt(SecretService.kt:227)
	at de.jepfa.yapm.service.secret.SecretService.encryptData(SecretService.kt:215)
	at de.jepfa.yapm.service.secret.SecretService.encryptPassword(SecretService.kt:165)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.moveToEnterMasterPasswordScreen(LoginEnterPinFragment.kt:140)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.access$moveToEnterMasterPasswordScreen(LoginEnterPinFragment.kt:41)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$onViewCreated$3$3.invoke(LoginEnterPinFragment.kt:125)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$onViewCreated$3$3.invoke(LoginEnterPinFragment.kt:109)
	at de.jepfa.yapm.service.secret.MasterPasswordService.getMasterPasswordFromStore(MasterPasswordService.kt:62)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.onViewCreated$lambda$2(LoginEnterPinFragment.kt:109)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment.$r8$lambda$rE_szBT3zcIN3lUfwWmeZShNVww(Unknown Source:0)
	at de.jepfa.yapm.ui.login.LoginEnterPinFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:8)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16220)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30891)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	... 3 more

************ APP INFORMATION ***********
Version: 1.9.0
Version Code: 109000
Database Version: 7
Vault Version: 2
Vault Cipher: AES_256
Vault Created At: on Oct 26, 2023 at 10:36
MP stored: false
MP stored with auth: false
Build Timestamp: Jan 6, 2024 07:48:43
Build Type: release

************ DEVICE INFORMATION ***********
Brand: samsung
Manufacturer: samsung
Device: r9q
Model: SM-G990U
Product: r9qsqw
Hardware: qcom
OS Build Id: TP1A.220624.014
NFC available: true
NFC enabled: false
Has StrongBox support: true
Has biometrics support: true
Has biometrics enrolled: true
Is device lock enabled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Notifications granted: true
Overlay dialog granted: true
Camera granted: false
Biometric granted: true

************ FIRMWARE ************
SDK: 33
Release: 13
Incremental: G990USQS9EWK1
Codename: REL
Security patch: 2023-11-01

**Comment by jenspfahl** [comment]
This is usually a temporary problem. After a while or a reboot of the phone it usually works again. With the next release a fix is on its way.
