### ISSUE TITLE
Error report from user (syorrs)

### ISSUE THREAD

**Issue by whathefoucault** [jenspfahl/ANOTHERpass#73]
I am unable to create backups. When I export the vault the app returns an error. Please help. 

************ APP INFORMATION ***********
Version: 1.9.4
Version Code: 109004
Database Version: 7
Vault Id (anonymized): syorrs
Vault Version: 2
Vault Cipher: AES_256
Vault Created At: on 14 Jun 2024 at 11:50
MP stored: true
MP stored with auth: true
Build Timestamp: 1 Jun 2024 02:50:13
Build Type: release
Debug Mode: false

************ DEVICE INFORMATION ***********
Brand: OnePlus
Manufacturer: OnePlus
Device: OP595DL1
Model: CPH2573
Product: CPH2573IN
Hardware: qcom
OS Build Id: UKQ1.230924.001
NFC available: true
NFC enabled: false
Has StrongBox support: true
Has biometrics support: true
Has biometrics enrolled: true
Is device lock enabled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Notifications granted: true
Overlay dialog granted: false
Camera granted: false
Biometric granted: true

************ FIRMWARE ************
SDK: 34
Release: 14
Incremental: U.R4T3.180c33a_1436b-ad85
Codename: REL
Security patch: 2024-05-05

************ APP-LOG ************
( 5556): 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-16 10:52:37.733 E/ANOSS/BACKUP( 5556): Caused by: android.os.RemoteException: Remote stack trace:
06-16 10:52:37.733 E/ANOSS/BACKUP( 5556): 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:820)
06-16 10:52:37.733 E/ANOSS/BACKUP( 5556): 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:341)
06-16 10:52:37.733 E/ANOSS/BACKUP( 5556): 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:164)
06-16 10:52:37.733 E/ANOSS/BACKUP( 5556): 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7432)
06-16 10:52:37.733 E/ANOSS/BACKUP( 5556): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2761)
06-16 10:52:37.733 E/ANOSS/BACKUP( 5556): 
06-16 10:52:41.193 I/ANOSS/LST( 5556): onPrepareOptionsMenu
06-16 10:52:51.310 I/ANOSS/LST( 5556): onResume

**Comment by jenspfahl** [comment]
That is unfortunate. How did you do the export? By "Share vault" or by "Save vault"?
I can see in your logs that a remote permission check failed. So I assume you want to store the vault in a remote folder. Is this correct? Does neither of both options work?
