### ISSUE TITLE
Trying to export vault, when I click share this error happens

### ISSUE THREAD

**Issue by soda92** [jenspfahl/ANOTHERpass#77]
************ CAUSE OF ERROR ************

java.lang.SecurityException: de.jepfa.yapm: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3183)
	at android.os.Parcel.createException(Parcel.java:3167)
	at android.os.Parcel.readException(Parcel.java:3150)
	at android.os.Parcel.readException(Parcel.java:3092)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5860)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1853)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1781)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
	at de.jepfa.yapm.usecase.vault.ShareVaultUseCase.startShareActivity(ShareVaultUseCase.kt:87)
	at de.jepfa.yapm.ui.exportvault.ExportVaultActivity.onCreate$lambda$6$lambda$5$lambda$4(ExportVaultActivity.kt:77)
	at de.jepfa.yapm.ui.exportvault.ExportVaultActivity.$r8$lambda$3aQGpOmFPyXnvVj0TW_oCAfBs24(Unknown Source:0)
	at de.jepfa.yapm.ui.exportvault.ExportVaultActivity$$ExternalSyntheticLambda4.invoke(D8$$SyntheticClass:0)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher.launch$lambda$1(UseCaseBackgroundLauncher.kt:28)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher.$r8$lambda$9FDVaJQajywsQZo2I0OIyr2mQKo(Unknown Source:0)
	at de.jepfa.yapm.ui.UseCaseBackgroundLauncher$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
	at de.jepfa.yapm.ui.AsyncWithProgressBar$3$1.invokeSuspend(AsyncWithProgressBar.kt:31)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6530aa6, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14469)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2648)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2822)
	at android.os.Binder.execTransactInternal(Binder.java:1505)
	at android.os.Binder.execTransact(Binder.java:1444)

************ APP INFORMATION ***********
Version: 2.0.2
Version Code: 200002
Database Version: 8
Vault Id (anonymized): eewyah
Vault Version: 2
Vault Cipher: AES_128
Vault Created At: on Aug 12, 2023 at 00:15
MP stored: true
MP stored with auth: true
Build Timestamp: Nov 4, 2024 14:23:44
Build Type: release
Debug Mode: false

************ DEVICE INFORMATION ***********
Brand: OnePlus
Manufacturer: OnePlus
Device: OnePlus8T
Model: KB2000
Product: OnePlus8T
Hardware: qcom
OS Build Id: AP2A.240905.003
NFC available: true
NFC enabled: false
Has StrongBox support: false
Has hardware backed TEE: false
Has biometrics support: true
Has biometrics enrolled: true
Is device lock enabled: true

************ PERMISSIONS ************
Read Storage granted: true
Read/write storage granted: true
Notifications granted: true
Overlay dialog granted: true
Camera granted: true
Biometric granted: true

************ FIRMWARE ************
SDK: 34
Release: 14
Incremental: aff46dfbc0
Codename: REL
Security patch: 2024-10-01

************ APP-ERROR-LOG ************

**Comment by jenspfahl** [comment]
Thanks for sending this error report and sorry for the trouble. It is a specific problem of Android 14 and I will fix it within the next few days. As a workaround you could save the vault file on the device and share it with a different app.

**Comment by soda92** [comment]
Thank you!

**Comment by jenspfahl** [comment]
I have fixed it and unleashed to F-Droid build pipeline. This usually takes a few days to publish on F-Droid app store. Let me know if you still encounter problems after version 2.0.3 is available.

**Comment by soda92** [comment]
Thanks again for this great software!
